	$(document).ready(function() {
		$(".css-a").hover(
			function(){
			$(".lup1a").slideUp("fast");
			},
			function(){
			$(".lup1a").slideDown("fast");
		});
		$(".css-b").hover(
			function(){
			$(".lup1b").slideUp("fast");
			},
			function(){
			$(".lup1b").slideDown("fast");
		});
		$(".css-c").hover(
			function(){
			$(".lup1c").slideUp("fast");
			},
			function(){
			$(".lup1c").slideDown("fast");
		});
		$(".css-d").hover(
			function(){
			$(".lup1d").slideUp("fast");
			},
			function(){
			$(".lup1d").slideDown("fast");
		});
		$(".css-e").hover(
			function(){
			$(".lup1e").slideUp("fast");
			},
			function(){
			$(".lup1e").slideDown("fast");
		});
		$(".css-f").hover(
			function(){
			$(".lup1f").slideUp("fast");
			},
			function(){
			$(".lup1f").slideDown("fast");
		});
		$(".css-g").hover(
			function(){
			$(".lup1g").slideUp("fast");
			},
			function(){
			$(".lup1g").slideDown("fast");
		});
		$(".css-h").hover(
			function(){
			$(".lup1h").slideUp("fast");
			},
			function(){
			$(".lup1h").slideDown("fast");
		});
	});